CREATE TABLE IF NOT EXISTS users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    country character varying(50),
    created_at DATETIME,
    email character varying(50),
    first_name character varying(50),
    gender character varying(20),
    last_name character varying(50),
    occupation character varying(50),
    password character varying(200),
    phone_number jsonb,
    region character varying(50),
    relationship_status character varying(50),
    username character varying(50),
    description character varying(700),
    updated_at DATETIME
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_statistics
(
    user_id bigint NOT NULL,
    friend_count bigint NOT NULL,
    new_notification_count bigint,
    seen_notification_count bigint NOT NULL,
    unseen_notification_count bigint NOT NULL,
    like_count bigint NOT NULL DEFAULT 0,
    post_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT user_statistics_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_statistics_user FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS notifications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content character varying(255),
    created_at DATETIME NOT NULL,
    link character varying(255),
    recipient_id bigint,
    seen boolean NOT NULL,
    sender_id bigint,
    target_id bigint,
    type character varying(255) NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (id),
    CONSTRAINT fk13vcnq3ukas06ho1yrbc5lrb5 FOREIGN KEY (sender_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE,
    CONSTRAINT fkqqnsjxlwleyjbxlmm213jaj3f FOREIGN KEY (recipient_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE,
    CONSTRAINT notifications_type_check CHECK (type::text = ANY (ARRAY['LIKE'::character varying, 'COMMENT'::character varying, 'FRIEND_REQUEST'::character varying]::text[]))
);

CREATE TABLE IF NOT EXISTS friendships
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at DATETIME,
    friend_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT friendships_pkey PRIMARY KEY (id),
    CONSTRAINT fk4mcscxflf13uk72aupf6uwbgn FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE,
    CONSTRAINT fkt0mh1j446gu5rqba17rnknuil FOREIGN KEY (friend_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE,
    CONSTRAINT friendships_status_check CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'NO_RELATIONSHIP'::character varying]::text[]))
);

CREATE TABLE IF NOT EXISTS posts
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    comment_status character varying(255),
    content text,
    created_at DATETIME,
    is_sensitive_content integer NOT NULL,
    is_subscription_only integer NOT NULL,
    privacy_setting character varying(255),
    seq integer NOT NULL,
    title text,
    type character varying(255),
    user_id bigint,
    CONSTRAINT posts_pkey PRIMARY KEY (id),
    CONSTRAINT fk5lidm6cqbc7u4xhqpxm898qme FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT posts_comment_status_check CHECK (comment_status::text = ANY (ARRAY['OPEN'::character varying, 'CLOSED'::character varying, 'ONLY_FOLLOWER'::character varying]::text[])),
    CONSTRAINT posts_privacy_setting_check CHECK (privacy_setting::text = ANY (ARRAY['PUBLIC'::character varying, 'FRIENDS'::character varying, 'PRIVATE'::character varying, 'WCV'::character varying, 'WCNY'::character varying]::text[])),
    CONSTRAINT posts_type_check CHECK (type::text = ANY (ARRAY['NORMAL'::character varying, 'POLL'::character varying]::text[]))
);

CREATE TABLE IF NOT EXISTS post_visibility_denies
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at DATETIME NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT post_visibility_denies_pkey PRIMARY KEY (id),
    CONSTRAINT fk3ti94u6urpjo30hepeknmffi3 FOREIGN KEY (post_id)
        REFERENCES posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fkhvdek2t0y94px6tsp9d5h23t6 FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS post_visibility_allows
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at DATETIME NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT post_visibility_allows_pkey PRIMARY KEY (id),
    CONSTRAINT fk2ybb2iqew2uxc4ibsfdjuc8bg FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fkitir425wr4bu5ujwxiewltdal FOREIGN KEY (post_id)
        REFERENCES posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS post_statistics
(
    post_id bigint NOT NULL,
    comment_count bigint NOT NULL,
    like_count bigint NOT NULL,
    CONSTRAINT post_statistics_pkey PRIMARY KEY (post_id),
    CONSTRAINT fk69n3kv4oskyufyclelj76620u FOREIGN KEY (post_id)
        REFERENCES posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS post_likes
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at DATETIME,
    user_id bigint,
    post_id bigint NOT NULL,
    CONSTRAINT post_likes_pkey PRIMARY KEY (id),
    CONSTRAINT fka5wxsgl4doibhbed9gm7ikie2 FOREIGN KEY (post_id)
        REFERENCES posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE,
    CONSTRAINT fkkgau5n0nlewg6o9lr4yibqgxj FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS post_attachments
(
    id character varying(255) NOT NULL,
    format character varying(255),
    mimetype character varying(255),
    post_id bigint NOT NULL,
    CONSTRAINT post_attachments_pkey PRIMARY KEY (id),
    CONSTRAINT fkdwocy2l1nlf11ebpfrax6sto1 FOREIGN KEY (post_id)
        REFERENCES posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS polls
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at DATETIME NOT NULL,
    updated_at DATETIME
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    post_id bigint NOT NULL,
    CONSTRAINT polls_pkey PRIMARY KEY (id),
    CONSTRAINT ukis80fe7d3qmglc2d1ro6d6u7y UNIQUE (post_id),
    CONSTRAINT fkf3lrqq3l3pri7vyykyf71dp2v FOREIGN KEY (post_id)
        REFERENCES posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS poll_questions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at DATETIME NOT NULL,
    expire_at DATETIME,
    title character varying(255),
    updated_at DATETIME
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    vote_count integer NOT NULL,
    poll_id bigint NOT NULL,
    CONSTRAINT poll_questions_pkey PRIMARY KEY (id),
    CONSTRAINT fkdiuqaq869156f0k67iwxvbysb FOREIGN KEY (poll_id)
        REFERENCES polls (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS comments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content text NOT NULL,
    created_at DATETIME NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE,
    CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id)
        REFERENCES posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS chat_rooms
(
    id character varying(26) NOT NULL,
    created_at DATETIME,
    last_message_at DATETIME,
    message_preview character varying(255),
    name character varying(255),
    type character varying(255) NOT NULL,
    CONSTRAINT chat_rooms_pkey PRIMARY KEY (id),
    CONSTRAINT chat_rooms_type_check CHECK (type::text = ANY (ARRAY['PRIVATE'::character varying, 'GROUP'::character varying]::text[]))
);

CREATE TABLE IF NOT EXISTS chat_room_members
(
    id character varying(26) NOT NULL,
    created_at DATETIME,
    last_seen_at DATETIME,
    unread_count bigint NOT NULL,
    chat_room_id character varying(26) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT chat_room_members_pkey PRIMARY KEY (id),
    CONSTRAINT fk6x7kwk21yt5odfxv5ubbrmo0h FOREIGN KEY (chat_room_id)
        REFERENCES chat_rooms (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE,
    CONSTRAINT fkbemsjj4g0iny4xpkvj5rwj6ab FOREIGN KEY (user_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS chat_messages
(
    id character varying(26) NOT NULL,
    created_at DATETIME,
    text character varying(255) NOT NULL,
    chat_room character varying(26) NOT NULL,
    sender_id bigint NOT NULL,
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
    CONSTRAINT fkdwchm3uojo7gxfenw1gorgmw5 FOREIGN KEY (chat_room)
        REFERENCES chat_rooms (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE,
    CONSTRAINT fkgiqeap8ays4lf684x7m0r2729 FOREIGN KEY (sender_id)
        REFERENCES users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);

CREATE TABLE IF NOT EXISTS chat_attachments
(
    id character varying(255) NOT NULL,
    link character varying(255),
    chat_message_id character varying(26) NOT NULL,
    CONSTRAINT chat_attachments_pkey PRIMARY KEY (id),
    CONSTRAINT fko9sv71fadi7nk0w7khvnp60iu FOREIGN KEY (chat_message_id)
        REFERENCES chat_messages (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE DELETE
);