-- =========================================
-- STORIES TABLE
-- =========================================
CREATE TABLE IF NOT EXISTS stories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    media_id bigint NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT stories_pkey PRIMARY KEY (id),

    CONSTRAINT fk_stories_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,

    CONSTRAINT fk_stories_media
        FOREIGN KEY (media_id)
        REFERENCES media (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_stories_user_id ON stories(user_id);
CREATE INDEX IF NOT EXISTS idx_stories_expires_at ON stories(expires_at);



-- =========================================
-- STORY VIEW TABLE
-- =========================================
CREATE TABLE IF NOT EXISTS story_view (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    story_id bigint NOT NULL,
    user_id bigint NOT NULL,
    viewed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT story_view_pkey PRIMARY KEY (id),

    CONSTRAINT fk_story_view_story
        FOREIGN KEY (story_id)
        REFERENCES stories (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,

    CONSTRAINT fk_story_view_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,

    -- Prevent same user from viewing same story multiple times (optional but recommended)
    CONSTRAINT uk_story_view UNIQUE (story_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_story_view_story_id ON story_view(story_id);
CREATE INDEX IF NOT EXISTS idx_story_view_user_id ON story_view(user_id);